### ISSUE TITLE
South integration needs tests

### ISSUE THREAD

**Issue by akshayjshah** [hearsaycorp/django-livefield#14]
We should add a test migration to make sure that the South integration works.

Sorry to keep piling on, @dyve - can you take this one on, too? I'd jump in, but I've never used South before.

**Comment by dyve** [comment]
Most of our projects have switched to Django 1.7 migrations, I don't think I'll get to testing South again.

**Comment by akshayjshah** [comment]
Fair enough - most of the community seems to be going the same way, so we can close this.
