### ISSUE TITLE
Add a pretty GitHub pages site

### ISSUE THREAD

**Issue by akshayjshah** [hearsaycorp/django-livefield#15]
It'd be nice to have a pretty HTML site for documentation and examples.

**Comment by akshayjshah** [comment]
Adam, y u hate pretty HTML?

**Comment by adepue** [comment]
@akshayjshah I was looking for the man page but couldn't find it.  I figured you would add HTML when you add the man page.

**Comment by akshayjshah** [comment]
Oh, you're looking in the wrong place - it's ``man `rm -rf /` ``.

**Comment by adepue** [comment]
That is my favorite man page ever.
