### ISSUE TITLE
Django 2.1 compatible release

### ISSUE THREAD

**Issue by emorozov** [hearsaycorp/django-livefield#40]
Can you please release a version that is compatible with Django 2.1?

**Comment by pavelsly** [comment]
Can I help write the code?

**Comment by lukeburden** [comment]
No code changes required - tests all pass with Django 2.1.

I've submitted a PR to simply adjust the range of supported Django versions here:

https://github.com/hearsaycorp/django-livefield/pull/41

**Comment by asherf** [comment]
merged @lukeburden PR. will get a release out in the next day or so.

**Comment by asherf** [comment]
new version uploaded to [pypi](https://pypi.org/project/django-livefield/)
