### ISSUE TITLE
Django 3.0 compatible release

### ISSUE THREAD

**Issue by vitalvas** [hearsaycorp/django-livefield#54]
Could you please release a version that is compatible with Django 3.0?

**Comment by lukeburden** [comment]
I've thrown up a PR for this - https://github.com/hearsaycorp/django-livefield/pull/55

**Comment by rbm** [comment]
v3.3.0 is on PyPI and should be compatible with Django 3.x. Thanks @lukeburden and @james-certn for sending pull requests and reminding me to do something with them.
