### ISSUE TITLE
Django 4.2 compatible release

### ISSUE THREAD

**Issue by james-certn** [hearsaycorp/django-livefield#59]
A [PR](https://github.com/hearsaycorp/django-livefield/pull/58) has already been opened by a new contributor (yay!).

@rbm, would it be possible to put together a new release?

**Comment by rbm** [comment]
@james-certn -- Thanks for filing the issue! And thanks @hernantz for the PR.

I'm not at Hearsay (the company behind `django-livefield`) these days and I don't think I can merge PRs or release to PyPI for this package any more. Let me reach out to some folks on the team there.

**Comment by rbm** [comment]
@james-certn @ibiternas will follow up about this (or have someone from the python infra team at Hearsay follow up) -- please allow a bit of time since I'm pretty sure it's a busy time over there, and 4.2 isn't officially out yet.

**Comment by hernantz** [comment]
@james-certn @rbm appreciate your help moving this forward!
@rbm this also adds support for 4.1 which has been released already

**Comment by james-certn** [comment]
Hey friends (@hernantz @ibiternas, @rbm) - just noting that Django 4.2 is released an now generally available to the public. Do we think we can nail down a timeline for getting a compatible release of `django-livefields` out? Thanks!

See [the PR](https://github.com/hearsaycorp/django-livefield/pull/58) for it. 🙏

**Comment by lopezm1** [comment]
@james-certn @hernantz 

Thank you for the contributions. Apologies for losing track of these issues. 

We have released 4.0.0 which offers Django 4.2 and Python 3.11 support. In the future release, we will extend this to Django 5 and Python 3.12 to keep this repo up to date.
